NAME = input('PLEASE ENTER YOUR NAME: ')
SID = int(input('PLEASE ENTER YOUR SID: '))
DEPARTMENT = input('PLEASE WRITE YOUR RESPECTIVE DEPARTMENT: ')
CGPA = float(input('ENTER YOUR CGPA: '))
name ='Hey,%s Here!'%(NAME)
sid ='My SID is %d'%(SID)
department_cgpa ='I am from %s department and my CGPA is %f'%(DEPARTMENT,CGPA)
print("THE OUTPUT IS:")
print(name)
print(sid)
print(department_cgpa)